export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST"
export const ALL_ORDER_SUCCESS = "ALL_ORDER_SUCCESS"
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL"

export const ORDER_SELLER_REQUEST = "ORDER_SELLER_REQUEST"
export const ORDER_SELLER_SUCCESS = "ORDER_SELLER_SUCCESS"
export const ORDER_SELLER_FAIL = "ORDER_SELLER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"