export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST"
export const ALL_ORDER_SUCCESS = "ALL_ORDER_SUCCESS"
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL"

export const ORDER_SELLER_REQUEST = "ORDER_SELLER_REQUEST"
export const ORDER_SELLER_SUCCESS = "ORDER_SELLER_SUCCESS"
export const ORDER_SELLER_FAIL = "ORDER_SELLER_FAIL"

export const ORDER_USER_REQUEST = "ORDER_USER_REQUEST"
export const ORDER_USER_SUCCESS = "ORDER_USER_SUCCESS"
export const ORDER_USER_FAIL = "ORDER_USER_FAIL"

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST"
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS"
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"