export const SET_DARK_MODE = "SET_DARK_MODE"

export const TOP_LOADING_BAR_MOVEMENT = "TOP_LOADING_BAR_MOVEMENT"

export const PRODUCT_CATEGORY = "PRODUCT_CATEGORY" 

export const CLEAR_ERRORS = "CLEAR_ERRORS"