export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"


export const LOAD_REQUEST = "LOAD_REQUEST"
export const LOAD_SUCCESS = "LOAD_SUCCESS"
export const LOAD_FAIL = "LOAD_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST"
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS"
export const PROFILE_UPDATE_RESET = "PROFILE_UPDATE_RESET"
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL"

export const PASSWORD_UPDATE_REQUEST = "PASSWORD_UPDATE_REQUEST"
export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS"
export const PASSWORD_UPDATE_RESET = "PASSWORD_UPDATE_RESET"
export const PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL"

export const FORGOT_UPDATE_REQUEST = "FORGOT_UPDATE_REQUEST"
export const FORGOT_UPDATE_SUCCESS = "FORGOT_UPDATE_SUCCESS"
export const FORGOT_UPDATE_FAIL = "FORGOT_UPDATE_FAIL"

export const ALL_USER_DATE_REQUEST  = " ALL_USER_DATE_REQUEST"
export const ALL_USER_DATE_SUCCESS = " ALL_USER_DATE_SUCCESS"
export const ALL_USER_DATE_FAIL = " ALL_USER_DATE_FAIL"

export const SELLER_USER_DATE_REQUEST  = "SELLER_USER_DATE_REQUEST"
export const SELLER_USER_DATE_SUCCESS = "SELLER_USER_DATE_SUCCESS"
export const SELLER_USER_DATE_FAIL = "SELLER_USER_DATE_FAIL"

export const RESET_UPDATE_REQUEST = "RESET_UPDATE_REQUEST"
export const RESET_UPDATE_SUCCESS = "RESET_UPDATE_SUCCESS"
export const RESET_UPDATE_FAIL = "RESET_UPDATE_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"